(in-package "OBJC-CFFI")

(defvar objc-typechar-map
  `((id "@")
    (class "#")
    (sel ":")
    (chr "c")
    (uchr "C")
    (sht "s")
    (usht "S")
    (int "i")
    (uint "I")
    (lng "l")
    (ulng "L")
    (flt "f")
    (dbl "d")
    (bfld "b")
    (void "v")
    (undef "?")
    (ptr "^")
    (charptr "*")
    (ary_begin "[")
    (ary_end "]")
    (union_begin "(")
    (union_end ")")
    (struct_begin "{")
    (struct_end "}")))

(defun objc-typechar-to-type (type)
  (loop for (sym typechar) in objc-typechar-map
       when (string= type typechar)
       return sym))