(defpackage "OBJC-CFFI"
  (:use "COMMON-LISP" "CFFI")
  (:export "GET-CLASS-LIST" "GET-CLASS-METHODS" "CLASS-IVARS" "PRIVATE-IVAR" "CLASS-HAS-PUBLIC-IVARS"
           "OBJC-SELECTOR" "OBJC-CLASS" "OBJC-METHOD" "OBJC-IVAR" "OBJC-OBJECT" "SUPER-CLASSES"
           "CLASS-GET-INSTANCE-METHOD" "CLASS-GET-CLASS-METHOD" "METHOD-TYPE-SIGNATURE"
           "OBJC-ID" "OBJC-SEL" "OBJC-CLASS-POINTER" "OBJC-BOOL")
  )

(defpackage "CL-OBJC"
  (:use "COMMON-LISP" "CFFI"))