\input texinfo
@setfilename cl-objc.info
@settitle cl-objc

@copying
Documentation for the Common Lisp ObjC Interface, version 1.0.

Copyright @copyright{} 2007 Geoff Cant, Luigi Panzeri

@quotation
Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved.
@end quotation
@end copying

@titlepage
@title Common Lisp ObjC Interface

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Common Lisp ObjC Interface Library

@insertcopying
@end ifnottex

@menu 
* Introduction::    What is CL-ObjC?
* Tutorial::        Brief Guide to CL-ObjC
* CFFI Bindings::   Using simple wrappers of ObjC FFI
* Lisp Wrappers::   Writing ObjC application using Common Lisp wrappers
* CLOS Wrappers::   The CLOS wrapper to ObjC object system
* Reader Macro::    Using the reader macro to write in ObjC style
* Implementation Notes::
* Examples::
* API Reference::
* Index::           Complete index.
@end menu

@node Introduction
@chapter Introduction

What is CL-ObjC?
Aims
Supported Architectures
Requirements
Limits
How and where to get it?
Installation (asdf, asdf-install)
Acknowledgments

@node Tutorial
@chapter Tutorial

Typed and Untyped

Getting a class
allocate an instance
call instance method
call class method

Using Lisp wrappers

Using Reader Macros


@node CFFI Bindings
@chapter CFFI Bindings

Type translators
Invoking methods
Getting information about classes and instances
How to wrap a new ObjC class library

@node Lisp Wrappers
@chapter Lisp Wrappers

@node CLOS Wrappers
@chapter CLOS Wrappers

@node Reader Macro
@chapter Reader Macro

@node Implementation Notes
@chapter Implementation Notes

@node Examples
@chapter Examples

@node API Reference
@chapter API Reference

@node Index
@unnumbered Index
@printindex cp
@bye
