#!/bin/sh

CONTENTS="$0"
LISPDIR=`dirname "$CONTENTS"`
CONTENTS=`dirname "$LISPDIR"`

if [ ! -e $LISPDIR/sbcl ]; then
    if [ ! "$(which sbcl)" ]; then
	echo "Error: SBCL is not in $LISPDIR nor in $PATH"
    else
	ln -s `which sbcl` $LISPDIR
    fi
fi

exec "$LISPDIR/sbcl" --eval "(asdf:oos 'asdf:load-op 'cl-objc)" --eval "(asdf:oos 'asdf:load-op 'swank)" --eval "(swank:create-server :port 5555 :dont-close t)" --eval "(asdf:oos 'asdf:load-op 'cl-objc.examples)" --eval "(cl-objc-examples:converter)"

