(defpackage "OBJC-CFFI"
  (:use "COMMON-LISP" "CFFI")
  (:export 

   "GET-CLASS-LIST" 
   "GET-CLASS-METHODS" 
   "OBJC-GET-CLASS"
   "CLASS-IVARS" 
   "PRIVATE-IVAR" 
   "CLASS-HAS-PUBLIC-IVARS"
   "SUPER-CLASSES"
   "CLASS-GET-INSTANCE-METHOD" 
   "CLASS-GET-CLASS-METHOD" 

   "SEL-NAME"

   "METHOD-TYPE-SIGNATURE"
   "METHOD-SELECTOR"

   "TYPED-OBJC-MSG-SEND" 
   "UNTYPED-OBJC-MSG-SEND" 

   "ADD-OBJC-METHOD" 

   "CFFI-TYPE-P"
   "OBJC-STRUCT-SLOT-VALUE"))

(defpackage "CL-OBJC"
  (:use "COMMON-LISP" "CFFI")
  (:export "INVOKE"
	   "SYMBOLS-TO-OBJC-SELECTOR"
	   "OBJC-SELECTOR-TO-SYMBOLS"))

(defpackage "OBJC-TYPES"
  (:use "COMMON-LISP" "YACC")
  (:export "PARSE-OBJC-TYPESTR" 
           "OBJC-UNKNOWN-TYPE" 
	   "TYPEMAP" 
	   "ENCODE-TYPES" 
	   "ENCODE-TYPE"))

(defpackage "OBJC-READER"
  (:use "COMMON-LISP" "OBJC-CFFI")
  (:export "ACTIVATE-OBJC-READER-MACRO" 
	   "RESTORE-READTABLE"
	   "*ACCEPT-UNTYPED-CALL*"))